/**
 * Les 99 Noms d'Allah (Asma'ul Husna) — liste traditionnelle,
 * avec translittération et signification en français.
 */
export type DivineName = {
  arabic: string;
  translit: string;
  fr: string;
};

export const ASMA_UL_HUSNA: DivineName[] = [
  { arabic: "الرَّحْمَنُ", translit: "Ar-Rahmān", fr: "Le Tout Miséricordieux" },
  { arabic: "الرَّحِيمُ", translit: "Ar-Rahīm", fr: "Le Très Miséricordieux" },
  { arabic: "الْمَلِكُ", translit: "Al-Malik", fr: "Le Souverain" },
  { arabic: "الْقُدُّوسُ", translit: "Al-Quddūs", fr: "Le Saint, Le Pur" },
  { arabic: "السَّلَامُ", translit: "As-Salām", fr: "La Paix, La Sécurité" },
  { arabic: "الْمُؤْمِنُ", translit: "Al-Mu'min", fr: "Le Rassurant, Le Fidèle" },
  { arabic: "الْمُهَيْمِنُ", translit: "Al-Muhaymin", fr: "Le Préservateur" },
  { arabic: "الْعَزِيزُ", translit: "Al-'Azīz", fr: "Le Tout-Puissant" },
  { arabic: "الْجَبَّارُ", translit: "Al-Jabbār", fr: "Celui qui domine et répare" },
  { arabic: "الْمُتَكَبِّرُ", translit: "Al-Mutakabbir", fr: "Le Suprême, Le Majestueux" },
  { arabic: "الْخَالِقُ", translit: "Al-Khāliq", fr: "Le Créateur" },
  { arabic: "الْبَارِئُ", translit: "Al-Bāri'", fr: "Celui qui donne l'existence" },
  { arabic: "الْمُصَوِّرُ", translit: "Al-Musawwir", fr: "Le Façonneur des formes" },
  { arabic: "الْغَفَّارُ", translit: "Al-Ghaffār", fr: "Le Grand Pardonneur" },
  { arabic: "الْقَهَّارُ", translit: "Al-Qahhār", fr: "Le Dominateur Suprême" },
  { arabic: "الْوَهَّابُ", translit: "Al-Wahhāb", fr: "Le Grand Donateur" },
  { arabic: "الرَّزَّاقُ", translit: "Ar-Razzāq", fr: "Le Grand Pourvoyeur" },
  { arabic: "الْفَتَّاحُ", translit: "Al-Fattāh", fr: "Celui qui ouvre et accorde la victoire" },
  { arabic: "الْعَلِيمُ", translit: "Al-'Alīm", fr: "L'Omniscient" },
  { arabic: "الْقَابِضُ", translit: "Al-Qābid", fr: "Celui qui retient" },
  { arabic: "الْبَاسِطُ", translit: "Al-Bāsit", fr: "Celui qui étend Sa générosité" },
  { arabic: "الْخَافِضُ", translit: "Al-Khāfid", fr: "Celui qui abaisse" },
  { arabic: "الرَّافِعُ", translit: "Ar-Rāfi'", fr: "Celui qui élève" },
  { arabic: "الْمُعِزُّ", translit: "Al-Mu'izz", fr: "Celui qui honore" },
  { arabic: "الْمُذِلُّ", translit: "Al-Mudhill", fr: "Celui qui rabaisse" },
  { arabic: "السَّمِيعُ", translit: "As-Samī'", fr: "Celui qui entend tout" },
  { arabic: "الْبَصِيرُ", translit: "Al-Basīr", fr: "Celui qui voit tout" },
  { arabic: "الْحَكَمُ", translit: "Al-Hakam", fr: "Le Juge Suprême" },
  { arabic: "الْعَدْلُ", translit: "Al-'Adl", fr: "Le Parfaitement Juste" },
  { arabic: "اللَّطِيفُ", translit: "Al-Latīf", fr: "Le Doux, Le Subtil" },
  { arabic: "الْخَبِيرُ", translit: "Al-Khabīr", fr: "Le Parfaitement Informé" },
  { arabic: "الْحَلِيمُ", translit: "Al-Halīm", fr: "L'Indulgent, Le Longanime" },
  { arabic: "الْعَظِيمُ", translit: "Al-'Azīm", fr: "L'Immense" },
  { arabic: "الْغَفُورُ", translit: "Al-Ghafūr", fr: "Le Pardonneur" },
  { arabic: "الشَّكُورُ", translit: "Ash-Shakūr", fr: "Le Très Reconnaissant" },
  { arabic: "الْعَلِيُّ", translit: "Al-'Aliyy", fr: "Le Très-Haut" },
  { arabic: "الْكَبِيرُ", translit: "Al-Kabīr", fr: "L'Infiniment Grand" },
  { arabic: "الْحَفِيظُ", translit: "Al-Hafīz", fr: "Le Gardien, Le Protecteur" },
  { arabic: "الْمُقِيتُ", translit: "Al-Muqīt", fr: "Le Nourricier" },
  { arabic: "الْحَسِيبُ", translit: "Al-Hasīb", fr: "Celui qui suffit et tient compte" },
  { arabic: "الْجَلِيلُ", translit: "Al-Jalīl", fr: "Le Majestueux" },
  { arabic: "الْكَرِيمُ", translit: "Al-Karīm", fr: "Le Très Généreux" },
  { arabic: "الرَّقِيبُ", translit: "Ar-Raqīb", fr: "Le Vigilant" },
  { arabic: "الْمُجِيبُ", translit: "Al-Mujīb", fr: "Celui qui exauce" },
  { arabic: "الْوَاسِعُ", translit: "Al-Wāsi'", fr: "L'Ample, L'Immense en dons" },
  { arabic: "الْحَكِيمُ", translit: "Al-Hakīm", fr: "L'Infiniment Sage" },
  { arabic: "الْوَدُودُ", translit: "Al-Wadūd", fr: "Le Bien-Aimant" },
  { arabic: "الْمَجِيدُ", translit: "Al-Majīd", fr: "Le Très Glorieux" },
  { arabic: "الْبَاعِثُ", translit: "Al-Bā'ith", fr: "Celui qui ressuscite" },
  { arabic: "الشَّهِيدُ", translit: "Ash-Shahīd", fr: "Le Grand Témoin" },
  { arabic: "الْحَقُّ", translit: "Al-Haqq", fr: "La Vérité" },
  { arabic: "الْوَكِيلُ", translit: "Al-Wakīl", fr: "Le Meilleur Garant" },
  { arabic: "الْقَوِيُّ", translit: "Al-Qawiyy", fr: "Le Très Fort" },
  { arabic: "الْمَتِينُ", translit: "Al-Matīn", fr: "L'Inébranlable" },
  { arabic: "الْوَلِيُّ", translit: "Al-Waliyy", fr: "Le Protecteur, L'Allié" },
  { arabic: "الْحَمِيدُ", translit: "Al-Hamīd", fr: "Le Digne de louange" },
  { arabic: "الْمُحْصِي", translit: "Al-Muhsī", fr: "Celui qui dénombre tout" },
  { arabic: "الْمُبْدِئُ", translit: "Al-Mubdi'", fr: "Celui qui donne l'origine" },
  { arabic: "الْمُعِيدُ", translit: "Al-Mu'īd", fr: "Celui qui fait revenir" },
  { arabic: "الْمُحْيِي", translit: "Al-Muhyī", fr: "Celui qui donne la vie" },
  { arabic: "الْمُمِيتُ", translit: "Al-Mumīt", fr: "Celui qui donne la mort" },
  { arabic: "الْحَيُّ", translit: "Al-Hayy", fr: "Le Vivant" },
  { arabic: "الْقَيُّومُ", translit: "Al-Qayyūm", fr: "Celui qui subsiste par Lui-même" },
  { arabic: "الْوَاجِدُ", translit: "Al-Wājid", fr: "Celui qui trouve tout ce qu'Il veut" },
  { arabic: "الْمَاجِدُ", translit: "Al-Mājid", fr: "Le Noble, L'Illustre" },
  { arabic: "الْوَاحِدُ", translit: "Al-Wāhid", fr: "L'Unique" },
  { arabic: "الْأَحَدُ", translit: "Al-Ahad", fr: "L'Un" },
  { arabic: "الصَّمَدُ", translit: "As-Samad", fr: "L'Absolu, Le Seul recours" },
  { arabic: "الْقَادِرُ", translit: "Al-Qādir", fr: "Le Puissant" },
  { arabic: "الْمُقْتَدِرُ", translit: "Al-Muqtadir", fr: "Le Détenteur absolu du pouvoir" },
  { arabic: "الْمُقَدِّمُ", translit: "Al-Muqaddim", fr: "Celui qui met en avant" },
  { arabic: "الْمُؤَخِّرُ", translit: "Al-Mu'akhkhir", fr: "Celui qui met en arrière" },
  { arabic: "الْأَوَّلُ", translit: "Al-Awwal", fr: "Le Premier" },
  { arabic: "الْآخِرُ", translit: "Al-Ākhir", fr: "Le Dernier" },
  { arabic: "الظَّاهِرُ", translit: "Az-Zāhir", fr: "L'Apparent" },
  { arabic: "الْبَاطِنُ", translit: "Al-Bātin", fr: "Le Caché" },
  { arabic: "الْوَالِي", translit: "Al-Wālī", fr: "Le Maître très proche" },
  { arabic: "الْمُتَعَالِي", translit: "Al-Muta'ālī", fr: "Le Sublime, L'Exalté" },
  { arabic: "الْبَرُّ", translit: "Al-Barr", fr: "Le Bienfaisant" },
  { arabic: "التَّوَّابُ", translit: "At-Tawwāb", fr: "L'Accueillant au repentir" },
  { arabic: "الْمُنْتَقِمُ", translit: "Al-Muntaqim", fr: "Celui qui rétribue avec justice" },
  { arabic: "الْعَفُوُّ", translit: "Al-'Afuww", fr: "Le Très Indulgent" },
  { arabic: "الرَّءُوفُ", translit: "Ar-Ra'ūf", fr: "Le Très Compatissant" },
  { arabic: "مَالِكُ الْمُلْكِ", translit: "Mālik-ul-Mulk", fr: "Le Maître du Royaume" },
  { arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ", translit: "Dhūl-Jalāli wal-Ikrām", fr: "Détenteur de la Majesté et de la Générosité" },
  { arabic: "الْمُقْسِطُ", translit: "Al-Muqsit", fr: "L'Équitable" },
  { arabic: "الْجَامِعُ", translit: "Al-Jāmi'", fr: "Le Rassembleur" },
  { arabic: "الْغَنِيُّ", translit: "Al-Ghaniyy", fr: "Le Riche, Celui qui se suffit" },
  { arabic: "الْمُغْنِي", translit: "Al-Mughnī", fr: "Celui qui enrichit" },
  { arabic: "الْمَانِعُ", translit: "Al-Māni'", fr: "Celui qui préserve et empêche" },
  { arabic: "الضَّارُّ", translit: "Ad-Dārr", fr: "Celui qui éprouve" },
  { arabic: "النَّافِعُ", translit: "An-Nāfi'", fr: "Celui qui accorde le bien" },
  { arabic: "النُّورُ", translit: "An-Nūr", fr: "La Lumière" },
  { arabic: "الْهَادِي", translit: "Al-Hādī", fr: "Le Guide" },
  { arabic: "الْبَدِيعُ", translit: "Al-Badī'", fr: "Le Créateur sans modèle" },
  { arabic: "الْبَاقِي", translit: "Al-Bāqī", fr: "L'Éternel, Le Permanent" },
  { arabic: "الْوَارِثُ", translit: "Al-Wārith", fr: "L'Héritier de toute chose" },
  { arabic: "الرَّشِيدُ", translit: "Ar-Rashīd", fr: "Le Guide parfait" },
  { arabic: "الصَّبُورُ", translit: "As-Sabūr", fr: "Le Très Patient" },
];
